### ISSUE TITLE
error downloading external emoji: 415

### ISSUE THREAD

**Issue by Sanqui** [tsudoko/pullcord#7]
`2018/11/12 22:32:53 downloading https://cdn.discordapp.com/emojis/396521772868042754.gif?size=2048`
`2018/11/12 22:32:53 [306193495234707456/347190075471298568] error downloading external emoji 396521772868042754: non-200 status code: 415`

415 is [Unsupported Media Type](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/415)

Basically a more exotic #6

**Comment by tsudoko** [comment]
I assume the emoji in the message looked like `<a:emojiname:396521772868042754>`? Check if it works now, should be fixed in bade38f3b881c68dcda39f1f2cf1828ba5a0cb3f.

**Comment by Sanqui** [comment]
Hm, there seems to be several messages like that:
```
40831:2018-11-12T22:32:08.566681+01:00	history	add	message	417835055927263243	289475509421735936			<:feelsblobman:396521772868042754>
42268:2018-11-12T22:32:24.904407+01:00	history	add	message	419714563215196162	289475509421735936			<:feelsblobman:396521772868042754>
42275:2018-11-12T22:32:24.905051+01:00	history	add	message	419714939213578250	289475509421735936			\\<:feelsblobman:396521772868042754>
42277:2018-11-13T20:13:02.207698+01:00	history	add	message	419715014463586305	139909890905866240			:`: <a:feelsblobman:396521772868042754> `
42285:2018-11-13T20:13:02.208367+01:00	history	add	message	419715394782363649	289475509421735936			:`: <a<:feelsblobman:396521772868042754>396521772868042754> `
42289:2018-11-13T20:13:02.208599+01:00	history	add	message	419715798140059669	197360711096074251			:`:: <a<:feelsblobman:396521772868042754>396521772868042754>`
```

Somebody was possibly testing something?  In any case:

```
2018/11/13 20:13:01 downloading https://cdn.discordapp.com/emojis/396521772868042754.gif?size=2048
2018/11/13 20:13:02 warning: animated version of emoji 396521772868042754 doesn't exist, trying png
```
This has been fixed, thank you!

**Comment by tsudoko** [comment]
Yeah, expected something like that. I couldn't test it myself because invalid emoji literals seem to be stripped serverside now 🤷
