### ISSUE TITLE
error downloading attachment: file name too long

### ISSUE THREAD

**Issue by Sanqui** [tsudoko/pullcord#9]
`2018/11/13 20:03:32 downloading https://cdn.discordapp.com/attachments/290646848778010624/290927371433934848/y7DmozupaxfEqzdwLLp245Yfj9FTx43j-kxqOKmDCcnINOm7JfEWhxWd2JB1Pth7M1C_YOsb8aod1ZJE1tV7GmFbVoMfuRILxqTiUKMeM1jrhsHV35wgsGfgIXUPynK0-NjU-bTucnB5TC-Fe-sKM0_jgQ-f9Ra_hUo9wh0TErh9m4in8vx9vBmGxuLbQj7N4m3hmbd_peALImzbsxLwogqaCankdspaAXY78Q5mVwLyabka3Tgk2Zuc19I7v2r_K_xJQiHZeCMkvj46F8tjDHtZxIQ8rHixnqyUPD3Eif0IMpOgvdnnvn2zFJUbpi7ELNTCvJ8JmwT9pT1laWliz07cuWbOFw7NjHUvUv-DwMCk2QZBxVUi9un6IRFPlGPR9onYuQOxZP0cbHFtQBIjdzfdAMtTDK05MJwEVqPZ5aR_uM0z4sdCH_bS_PDzxWdLiXkV1O352UgZBDwkl_VYZrfHkE36C-CgqnHj098wHvAPFoKoskHmJ0S5rUbf..png`
`2018/11/13 20:03:33 [162218687514804224/290646848778010624] error downloading attachment 290927371433934848: open attachments/290646848778010624/290927371433934848/y7DmozupaxfEqzdwLLp245Yfj9FTx43j-kxqOKmDCcnINOm7JfEWhxWd2JB1Pth7M1C_YOsb8aod1ZJE1tV7GmFbVoMfuRILxqTiUKMeM1jrhsHV35wgsGfgIXUPynK0-NjU-bTucnB5TC-Fe-sKM0_jgQ-f9Ra_hUo9wh0TErh9m4in8vx9vBmGxuLbQj7N4m3hmbd_peALImzbsxLwogqaCankdspaAXY78Q5mVwLyabka3Tgk2Zuc19I7v2r_K_xJQiHZeCMkvj46F8tjDHtZxIQ8rHixnqyUPD3Eif0IMpOgvdnnvn2zFJUbpi7ELNTCvJ8JmwT9pT1laWliz07cuWbOFw7NjHUvUv-DwMCk2QZBxVUi9un6IRFPlGPR9onYuQOxZP0cbHFtQBIjdzfdAMtTDK05MJwEVqPZ5aR_uM0z4sdCH_bS_PDzxWdLiXkV1O352UgZBDwkl_VYZrfHkE36C-CgqnHj098wHvAPFoKoskHmJ0S5rUbf..png.part: file name too long`

The file name _is_ obscenely long, however, as it stands this prevents the Discord server from being archived.  Such a file is probably best skipped.

**Comment by tsudoko** [comment]
I don't like the idea of missing some files just because their names are too long, but yeah, I should've expected something like that would happen when archiving is done to a regular filesystem. I'm thinking of adding an additional optional `origname` field to the `attachment` record and truncating the downloaded filename to something sane if it's too long, what do you think?

**Comment by Sanqui** [comment]
Sounds reasonable to me!
